# ondrejsika.com jekyll config
name: ondrejsika.com
future: false
highlighter: pygments

exclude:
  - edit
  # Default
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/