version: "3.7"
services:
  site:
    labels:
      traefik.frontend.rule: Host:ondrejsika.com,www.ondrejsika.com,personal.ondrejsika.com,os.oxs.cz
      traefik.enable: 'true'
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
