#!/bin/bash
# MySQL Backup
# author: Ondrej Sika
#         http://ondrejsika.com/
#         dev@ondrejsika.com

USER=$1
PASSWORD=$2
OUTPUTDIR=$3

DATE=$(date +%Y-%m-%d)
OUTPUTDIR=$OUTPUTDIR${DATE}

mkdir -p $OUTPUTDIR

databases=`mysql --user=$USER --password=$PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema)"`
for db in $databases; do
    echo $db
    mysqldump --force --opt --user=$USER --password=$PASSWORD --databases $db 2>/dev/null | gzip > "$OUTPUTDIR/$db.sql.gz"
    mysqldump --force --opt --user=$USER --password=$PASSWORD --databases $db > "$OUTPUTDIR/$db.sql" 2>/dev/null
done