name: Build Docker Images on Pull Request

on:
  pull_request:
    branches: [ "*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Only
      run: make docker-build
